1DaXInTbOFrTdNW8ep3rZ8JuDtE:
  CopyKey: false
  Enabled: true
  Endpoints:
  - ID: 1DhH9WzuUwyem16gLKUjz0XyJGc
    Host: 172.16.1.146
    Port: "1935"
    App: live
    Stream: 41a11e05-f250-4e54-86f8-6c90d660971e
    Enabled: true
